flowchart TB
    subgraph Input["<font size=+1><b>Input</b></font>"]
        vid["<b>Input Video</b>"] --> fe["<b>Frame Extraction</b>"]
        fe --> frames["<b>Extracted Frames</b>"]
    end
    
    subgraph Auto["<font size=+1><b>Automated Detection</b></font>"]
        frames --> f2["<b>Florence-2 Detection</b>"]
        f2 --> f2bb["<b>Initial Bounding Boxes</b>"]
        f2bb --> sam2["<b>SAM2 Segmentation</b>"]
        sam2 --> sambb["<b>Refined Bounding Boxes</b>"]
    end
    
    subgraph Filter["<font size=+1><b>Filtering Pipeline</b></font>"]
        sambb --> size["<b>Size Filter</b> <br> <i>Removes objects <0.3% of frame size</i>"]
        size --> overlap["<b>Overlap Detection</b> <br> <i>Removes intersecting boxes</i>"]
        overlap --> crop["<b>Dynamic Cropping</b> <br> <i>Maximizes background while maintaining single object</i>"]
    end

    yolo["<font size=+1><b>YOLO Pre-annotation <br> Inference</b></font><br>Future additional step"] -.-> cvat
    
    subgraph Manual["<font size=+1><b>Manual Verification</b></font>"]
        crop --> cvat["<b>CVAT Review</b>"]
        cvat --> speciesID["<b>Species Classification</b>"]
        speciesID --> add["<b>Additional Annotations</b>"]
    end
    
    subgraph Model["<font size=+1><b>Model Development</b></font>"]
        add --> train["<b>YOLO Training</b>"]
        train --> inf["<b>YOLO Inference</b>"]
    end
    
    subgraph Output["<font size=+1><b>Output</b></font>"]
        inf --> maxn["<b>MaxN Generation</b>"]
        inf --> sac["<b>Species Accumulation Curve</b>"]
    end

    style Input fill:#ffffff
    style Auto fill:#e6f3ff
    style Filter fill:#fff0e6
    style Manual fill:#f0f9e8
    style Model fill:#f5e6ff
    style Output fill:#ffffff
    style yolo fill:#e6f3ff
